module.exports = {
  apps: [
    {
      name: 'HHSB',
      script: 'dist/server.js',
      env: {
        NODE_ENV: 'development',
        SECRET: 'HHSB',
        LYRICIST_TOKEN: 'UJYTnEMS0QZluVoY_1yooeL3OHXnsv9ShkAVK48GKjCJvvN4zYVrR60FJwnrnLeb',
        DATABASE_URL: 'mongodb://hhsb:superpass@hhsb-dev-env-shard-00-00-e2dry.mongodb.net:27017,hhsb-dev-env-shard-00-01-e2dry.mongodb.net:27017,hhsb-dev-env-shard-00-02-e2dry.mongodb.net:27017/hhsb?ssl=true&replicaSet=HHSB-Dev-Env-shard-0&authSource=admin',
        SMTP_HOST: 'smtp.postmarkapp.com',
        SMTP_PORT: 587,
        SMTP_USER: '7878f983-ac7c-4abb-99aa-96964e9246ea',
        SMTP_PASS: '7878f983-ac7c-4abb-99aa-96964e9246ea',
        CLIENT_URL: 'https://quote.vote',
        FROM_EMAIL: 'admin@quote.vote',
        REQUEST_ACCESS_URL: 'https://comment.quote.vote/auth/request-access',
        SANDBOX_STRIPE_SECRET_KEY: 'sk_test_51HKHNzGRGwUA6VaVMFGDIottzcDOihSfghqgvrumJCMH4eqwVA6GOO9oFvc1Aqd0FU8IhKZEHliLiMRff0eAx3eR00rXSnzgmF',
        LIVE_STRIPE_SECRET_KEY: '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',
        TO_INVESTOR_EMAIL: 'olivermolina10@gmail.com,louisgirifalco@gmail.com',
        STRIPE_ENVIRONMENT: 'production',
      },
      env_production: {
        NODE_ENV: 'production',
        SECRET: 'HHSB',
        LYRICIST_TOKEN: 'UJYTnEMS0QZluVoY_1yooeL3OHXnsv9ShkAVK48GKjCJvvN4zYVrR60FJwnrnLeb',
        DATABASE_URL: 'mongodb://hhsb:superpass@hhsb-dev-env-shard-00-00-e2dry.mongodb.net:27017,hhsb-dev-env-shard-00-01-e2dry.mongodb.net:27017,hhsb-dev-env-shard-00-02-e2dry.mongodb.net:27017/hhsb?ssl=true&replicaSet=HHSB-Dev-Env-shard-0&authSource=admin',
        SMTP_HOST: 'smtp.postmarkapp.com',
        SMTP_PORT: 587,
        SMTP_USER: '7878f983-ac7c-4abb-99aa-96964e9246ea',
        SMTP_PASS: '7878f983-ac7c-4abb-99aa-96964e9246ea',
        CLIENT_URL: 'https://quote.vote',
        FROM_EMAIL: 'admin@quote.vote',
        REQUEST_ACCESS_URL: 'https://quote.vote/auth/request-access',
        SANDBOX_STRIPE_SECRET_KEY: 'sk_test_51HKHNzGRGwUA6VaVMFGDIottzcDOihSfghqgvrumJCMH4eqwVA6GOO9oFvc1Aqd0FU8IhKZEHliLiMRff0eAx3eR00rXSnzgmF',
        LIVE_STRIPE_SECRET_KEY: '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',
        TO_INVESTOR_EMAIL: 'olivermolina10@gmail.com,louisgirifalco@gmail.com',
        STRIPE_ENVIRONMENT: 'production',
        APOLLO_KEY: 'service:hhsb-omolina:Cv1yGx3lnsFeLpXjXufgMg',
      },
    },
  ],
};